const songs=[
{id:1,title:'Amazing Grace',key:'G',tempo:72,style:'Hymn • Gentle',time:'3/4',set:'Sunday Mass',sections:[
{name:'VERSE 1',chords:'G   C   G',cue:'SOFT',level:'soft',lyrics:'Amazing grace, how sweet the sound\nThat saved a soul like me'},
{name:'VERSE 2',chords:'G   C   G   D',cue:'BUILD',level:'build',lyrics:'Through many dangers, toils and snares\nWe have already come'},
{name:'FINAL',chords:'G   C   G   D   G',cue:'FULL CHOIR • LOUD',level:'loud',lyrics:'Grace will lead us home'}]},
{id:2,title:'Here I Am, Lord',key:'G',tempo:76,style:'Worship • Prayerful',time:'4/4',set:'Sunday Mass',sections:[{name:'VERSE',chords:'G   C   G   D',cue:'SOFT',level:'soft',lyrics:'Sample lyric line for your choir\nReplace this with your authorised lyrics'},{name:'CHORUS',chords:'C   G   D   G',cue:'BUILD → FULL',level:'build',lyrics:'Sample chorus line\nEveryone joins here'}]},
{id:3,title:'Choir Practice Song',key:'C',tempo:92,style:'Contemporary',time:'4/4',set:'Practice',sections:[{name:'VERSE',chords:'C   Am   F   G',cue:'SOLO',level:'solo',lyrics:'Soloist begins this section softly'},{name:'CHORUS',chords:'F   G   C',cue:'FULL CHOIR • LOUD',level:'loud',lyrics:'All voices enter together'}]}
];
let page='home',selected=null,mode='singer',query='';
function render(){const a=document.querySelector('#app'); if(page==='home'){let f=songs.filter(s=>s.title.toLowerCase().includes(query.toLowerCase()));a.innerHTML=`<header class='top'><div class='brand'>HOLY ROSARY ENGLISH CHOIR</div><h1>Our Choir Songbook 🎵</h1><input class='search' id='q' placeholder='🔎 Search songs, key or style…' value='${query}'></header><main class='wrap'><div class='nav'><button class='active'>Songs</button><button>Sunday Setlist</button><button>♡ Favourites</button></div><h2>${query?'Search Results':'This Sunday'}</h2>${f.map(songCard).join('')||`<div class='empty'>No songs found</div>`}</main>`;document.querySelector('#q').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('[data-song]').forEach(x=>x.onclick=()=>{selected=+x.dataset.song;page='song';render()});}else renderSong(a)}
function songCard(s){return `<div class='card song' data-song='${s.id}'><h3>${s.title}</h3><div class='meta'>Key ${s.key} · ${s.tempo} BPM · ${s.time}</div><span class='tag'>${s.style}</span><span class='tag'>${s.set}</span></div>`}
function renderSong(a){let s=songs.find(x=>x.id===selected);a.innerHTML=`<main class='wrap'><button class='back' id='back'>← Songbook</button><div class='songhead'><div class='brand' style='color:#7a294a'>HOLY ROSARY ENGLISH CHOIR</div><h2>${s.title}</h2><div class='meta'>Key <b>${s.key}</b> · ${s.tempo} BPM · ${s.time} · ${s.style}</div></div><div class='controls'><button class='${mode==='singer'?'on':''}' data-mode='singer'>🎤 Singer</button><button class='${mode==='guitar'?'on':''}' data-mode='guitar'>🎸 Guitar</button><button class='${mode==='piano'?'on':''}' data-mode='piano'>🎹 Piano</button><button>− Transpose</button><button>+ Transpose</button></div>${s.sections.map(sec=>`<section class='section'><div class='sectionTitle'>${sec.name}</div>${mode!=='singer'?`<div class='chords'>${sec.chords}</div>`:''}<div class='lyric ${sec.level}'><div class='cue'>${sec.cue}</div>${sec.lyrics.replaceAll('\n','<br>')}</div></section>`).join('')}${mode!=='singer'?diagrams(s,mode):''}</main>`;document.querySelector('#back').onclick=()=>{page='home';render()};document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{mode=x.dataset.mode;render()})}
function diagrams(s,m){let cs=[...new Set(s.sections.flatMap(x=>x.chords.split(/\s+/)).filter(Boolean))].slice(0,6);return `<h3>${m==='guitar'?'🎸 Guitar chord shapes':'🎹 Piano chord notes'}</h3><div class='diagram'>${cs.map(c=>`<div class='card'><b style='color:#c4212f'>${c}</b><div class='fret'>${m==='guitar'?'● ─ ●\n│ ● │\n● │ ●':'▯▮▯▯▮▯▮'}</div></div>`).join('')}</div>`}
render();
